name: $pluginName
main: $pluginMain
api-version: "1.17"
authors: $authors
version: $version
description: Dashboard for Minecraft.
libraries:
  - org.jetbrains.kotlinx:kotlinx-coroutines-core:1.5.2
  - org.jetbrains.kotlinx:kotlinx-serialization-json:1.2.2
  - io.ktor:ktor-server-netty:1.6.1
  - io.ktor:ktor-jackson:1.6.1
  - io.github.monun:kommand:2.6.6
  - at.favre.lib:bcrypt:0.9.0
